### ISSUE TITLE
NullPointerException in java.util.StringTokenizer (ResourceSender.java:)

### ISSUE THREAD

**Issue by Dymeth** [FatSaw/AMusic#5]
```
Exception in thread "Thread-420" java.lang.NullPointerException: Cannot invoke "String.length()" because "str" is null
       at java.base/java.util.StringTokenizer.<init>(StringTokenizer.java:199)
       at java.base/java.util.StringTokenizer.<init>(StringTokenizer.java:236)
       at me.bomb.amusic.ResourceSender.run(ResourceSender.java:27)
```

https://github.com/FatSaw/AMusic/blob/main/amusic_core/src/main/java/me/bomb/amusic/resourceserver/ResourceSender.java#L29

The exception seems to occur if an application other than the Minecraft web client connects to the web server

**Comment by Dymeth** [comment]
Great, thanks. If the problem happens again, I'll report it
